name: CI pipeline

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build-and-verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Verify Architecture
        run: mvn clean verify

      - name: Upload modulith Diagrams
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 'modulith docs'
          path: target/modulith-docs/*.png

  docker-build:
     needs: build-and-verify
     runs-on: ubuntu-latest
     if: github.event.name == 'push

     steps:
       - uses: actions/checkout@v4

       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3

       - name: Build Docker Image (Layered)
         uses: docker/build-push-action@v5
         with:
           context: .
           push: false
           tags: e-shop:latest
           cache-from: type=gha
           cache-to: type=gha,mode=max